### ISSUE TITLE
[FR] Add Alpine as base Docker image flavor

### ISSUE THREAD

**Issue by ngosang** [PhilipMay/smart-prom-next#40]
Use Alpine as base Docker image. The main benefit is reduce the Docker image size.
Example => https://github.com/ngosang/urbackup-exporter/blob/master/DockerfileAlpine

**Comment by PhilipMay** [comment]
Good point. Thanks for the suggestion @ngosang .

I had deliberately chosen the slim debian, because I think that the image is virtually never used alone. 
Docker usually runs other images. Since Debian Slim is also used in other images, it does not matter. 
The base image is there more or less as it is. Then the size no longer plays a role.

What do you think?

Anyway. I could provide both.
A Debian Slim version and an Alpine version.

Do you want to contibute an Alpine version?

**Comment by ngosang** [comment]
I just opened another issue. It's not working for me ATM.
In this repository you have the 2 Dockerfiles and the GitHub action to publish both images => https://github.com/ngosang/urbackup-exporter
It's another Prometheus exporter in Python so it should be copy&paste.

**Comment by PhilipMay** [comment]
Thanks for your link and "template" @ngosang 

I added an Alpine flavor in Version "0.0.4rc1" - could you maybe test it please?

https://github.com/PhilipMay/smart-prom-next/pkgs/container/smart-prom-next/29988670?tag=0.0.4rc1-alpine

**Comment by PhilipMay** [comment]
@ngosang on my private bare metal docker installation the alpine image works...

**Comment by ngosang** [comment]
Tested. It works well but it's possible to reduce Docker' images size to half. You can pen another issue for that.

![image](https://user-images.githubusercontent.com/10577978/181371050-417861d2-d880-41bc-9dba-bc915e9084af.png)

**Comment by PhilipMay** [comment]
Thanks for testing. Does that mean that I can also close #41 ?

@ngosang what do you mean by "You can pen another issue for that."

**Comment by ngosang** [comment]
> it's possible to reduce Docker' images size to half. (if you do some changes in the Dockerfiles to avoid caching files and reduce the number of layers)

You can open another issue for that.

**Comment by PhilipMay** [comment]
> You can open another issue for that.

Ok - done in #45

**Comment by PhilipMay** [comment]
closing
